spring.application.name=Assignment1

openai.api-key=${OPENAI_API_KEY:}

spring.threads.virtual.enabled=true
spring.main.keep-alive=true
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s